version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      - POSTGRES_PASSWORD=kiq01
      - POSTGRES_USER=kiq 
      - POSTGRES_DB=base
    ports:
      - 5433:5432
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    ports:
      - 8100:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=kiq@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin1 
    depends_on:
      - db

networks:
  base:
      name: airflow_default
      external: true