version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres1
    ports:
      - 5433:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=kiq@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin1 
    depends_on:
      - db